// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXI0MpJOuIHJtlHOGdE1NzDF_CpQLxTtI',
    appId: '1:1048724494786:web:0f72bf1a48a1230ce2de5b',
    messagingSenderId: '1048724494786',
    projectId: 'advmobprog-new',
    authDomain: 'advmobprog-new.firebaseapp.com',
    storageBucket: 'advmobprog-new.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_NGDiUdqWW944XYspCwvt8kxw_iZcph0',
    appId: '1:1048724494786:android:66a5863cfa872ec4e2de5b',
    messagingSenderId: '1048724494786',
    projectId: 'advmobprog-new',
    storageBucket: 'advmobprog-new.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQWGCMr1z087VRgCl_5afSUV06mRNfMxs',
    appId: '1:1048724494786:ios:e8819a350629525fe2de5b',
    messagingSenderId: '1048724494786',
    projectId: 'advmobprog-new',
    storageBucket: 'advmobprog-new.firebasestorage.app',
    iosBundleId: 'com.example.mobprogact',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQWGCMr1z087VRgCl_5afSUV06mRNfMxs',
    appId: '1:1048724494786:ios:e8819a350629525fe2de5b',
    messagingSenderId: '1048724494786',
    projectId: 'advmobprog-new',
    storageBucket: 'advmobprog-new.firebasestorage.app',
    iosBundleId: 'com.example.mobprogact',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXI0MpJOuIHJtlHOGdE1NzDF_CpQLxTtI',
    appId: '1:1048724494786:web:c4560e264db2c227e2de5b',
    messagingSenderId: '1048724494786',
    projectId: 'advmobprog-new',
    authDomain: 'advmobprog-new.firebaseapp.com',
    storageBucket: 'advmobprog-new.firebasestorage.app',
  );
}
